### ISSUE TITLE
macOS Sierra 10.12.6 libsiftgpu.so failed to build

### ISSUE THREAD

**Issue by hippyvanman** [luckybulldozer/VisualSFM_OS_X_Installer#44]
Hi,

Tried uninstalling brew (and then reinstalling through the installer), also tried separately installing Xcode command line tools, any suggestions?

-----------------------------------------------------

Dan Monaghan's VSFM and PMVS installer for OS X

About to check to see if you have the Brew Package Manager
Great, you've got brew... Continuing
wget is already installed, OK
About to install xcode select
Hit Enter after it's installed
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
Checking we have the right version of XQuartz

	<string>2.7.8</string>
xquartz_version_result=0
Your version of XQuartz is 2.7.8 - perfect.

Ok, now you have to should have either...

1. Already had the correct version of XQuartz, so I'm continuing...

2. Had to have installed XQuartz and just logged out and back in...

Ready to continue the next installation of VSFM & PMVS   (press ENTER)

Installing Brew packages... this can take quite a long time
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
faas-cli           metaproxy          pazpar2            sops

Warning: jpeg 9b is already installed
Warning: gdk-pixbuf 2.36.9 is already installed
Warning: cairo 1.14.10 is already installed
Warning: freetype 2.8 is already installed
Warning: Already linked: /usr/local/Cellar/freetype/2.8
To relink: brew unlink freetype && brew link freetype
Warning: pango 1.40.11 is already installed
Warning: Already linked: /usr/local/Cellar/pixman/0.34.0_1
To relink: brew unlink pixman && brew link pixman
Warning: Already linked: /usr/local/Cellar/fontconfig/2.12.4
To relink: brew unlink fontconfig && brew link fontconfig
#############################################                             63######################################################################## 100.0%
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/formula.rb:2373:in `fails_with'

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

Warning: gtk+ 2.24.28 is already installed
Warning: glew 2.1.0 is already installed
Warning: gsl 2.4 is already installed
Warning: boost 1.65.0 is already installed
Warning: intltool 0.51.0 is already installed
Warning: cmake 3.9.1 is already installed
Warning: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
Warning: gcc@4.9 4.9.4 is already installed
Warning: devil 1.8.0_1 is already installed
Warning: pkg-config 0.29.2 is already installed
Zip file is present, so just unzipping, removing old dir to install so we don't have any conflicts
Archive:  VisualSFM_osx_64bit.zip
   creating: vsfm/
   creating: vsfm/bin/
   creating: vsfm/build/
   creating: vsfm/lib/
  inflating: vsfm/lib/blas.a         
  inflating: vsfm/lib/lapack.a       
  inflating: vsfm/lib/libf2c.a       
  inflating: vsfm/lib/libjpeg.a      
  inflating: vsfm/lib/VisualSFM.a    
  inflating: vsfm/makefile           
  inflating: vsfm/README             
Changing VSFM GCC to Brews gcc-4.9
Changing /usr/x11/lib to OS X default /opt/x11/lib
About to make...
mkdir -p build
mkdir -p bin 
cd build; ar -x ../lib/VisualSFM.a; cd ..;
g++-4.9 -w -o bin/VisualSFM build/*.* -L/usr/local/lib -L/opt/X11/lib -pthread -lGL -lGLU -lX11 -ldl -L/usr/local/Cellar/gtk+/2.24.28/lib -L/usr/local/Cellar/pango/1.40.11/lib -L/usr/local/Cellar/atk/2.24.0/lib -L/usr/local/Cellar/cairo/1.14.10/lib -L/usr/local/Cellar/gdk-pixbuf/2.36.9/lib -L/usr/local/Cellar/glib/2.52.3/lib -L/usr/local/Cellar/pango/1.40.11/lib -L/usr/local/Cellar/glib/2.52.3/lib -L/usr/local/Cellar/fontconfig/2.12.4/lib -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/glib/2.52.3/lib -L/usr/local/opt/gettext/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lfontconfig -lfreetype -lgthread-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation lib/lapack.a lib/blas.a lib/libf2c.a lib/libjpeg.a 
rm -f build/*.*
VSFM application built... moving on
LIB_SIFT_GPU is present, skipping download and unzip. removing old dir to install so we don't have any conflicts
Archive:  sift_gpu.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of sift_gpu.zip or
        sift_gpu.zip.zip, and cannot find sift_gpu.zip.ZIP, period.
/Users/joshwolstenholme/VisualSFM_OS_X_Installer-master/vsfm_os_x_installer.sh: line 261: cd: SiftGPU: No such file or directory
Disable Cuda Flags
sed: makefile: No such file or directory
Changing march from native core2 in makefile
sed: makefile: No such file or directory
Changing to prefer GLUT
sed: makefile: No such file or directory
Removing -L/opt/local/lib from makefile
sed: makefile: No such file or directory
Changing /usr/x11/lib to OS X default /opt/x11/lib
sed: makefile: No such file or directory
Disable TestWin build for this OS X build
sed: makefile: No such file or directory
make: *** No rule to make target `sift_gpu'.  Stop.
libsiftgpu.so failed to build.  Halting.

**Comment by Ninerian** [comment]
I solved this problem by download the zip from https://github.com/pitzer/SiftGPU and disabling the lines 250 to 258. 

After that you also have to change the following lines and replace every `sed -i ''` to `sed -i `

**Comment by ghalusa** [comment]
@Ninerian - You said "disabling the lines 250 to 258"... _which file?_

Then, you said, "After that you also have to change the following lines and replace every sed -i '' to sed -i"... _Again which file?_

**Comment by ghalusa** [comment]
@luckybulldozer - So, _the reason why_ this is happening... is due to the fact that the `sift_gpu.zip` file size is zero bytes.

![screen shot 2017-09-16 at 1 42 07 am](https://user-images.githubusercontent.com/1112193/30509515-509d8cd6-9a80-11e7-8ebd-c715bf320c74.png)

Just thought you should know...

**Comment by Ninerian** [comment]
@luckybulldozer @ghalusa the main reason is, that the url you are requesting for the sift_gpu.zip doesn’t exist and it returns a cgi file, which is renamed into a zip file. Then the unzip operation breaks with an error.

My workaround is to edit the install shell file in the mentioned way. A better solution would be to use the url of the GitHub Repo of siftGPU.

The second change I made could be only for my system. The sed commands like ‘sed -i '' -e "s/${S}/${R}/" makefile_no_gpu’ resolved in an file not found error, as the arguments are wrong. I changed it to ‘sed -i -e "s/${S}/${R}/" makefile_no_gpu’ and it worked.

**Comment by sheishistoric** [comment]
@Ninerian made these changes, still having the same issue - any suggestions?
